Repository CMPUT301F21T19/Habitappt, pull requests merged in 2021-11, with the labels that each got.

#71 Remove event image (if existing) from storage complete
  app/src/main/java/com/CMPUT301F21T19/habitappt/Habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/SharedHelper.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_event.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/view_habit.java
Labels: enhancement

#94 fixed incorrect deletion of habit event when cancel is selected
  app/src/main/java/com/CMPUT301F21T19/habitappt/SharedHelper.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_event.java
Labels: fix

#155 added intent test for US.01.06.01 and refactored habit list items
  .idea/misc.xml
  app/src/androidTest/java/com/CMPUT301F21T19/habitappt/US_01_06_01_Test.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/abstract_habit_list_fragment.java
  app/src/main/res/layout/habit_list_item.xml
Labels: fix

#153 Javadoc for a couple of classes & also added scores method
  app/src/main/java/com/CMPUT301F21T19/habitappt/Habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/SharedHelper.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_event.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/view_habit.java
Labels: documentation

#154 Added Javadocs for a bunch of classes. See comments
  app/src/androidTest/java/com/CMPUT301F21T19/habitappt/HabitTest.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/EventList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitEvent.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitList.java
Labels: documentation

#157 Added some more Javadoc
  app/build.gradle
  app/src/androidTest/java/com/CMPUT301F21T19/habitappt/addHabitTest.java
  app/src/androidTest/java/com/CMPUT301F21T19/habitappt/removeHabitTest.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/LoginActivity.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/MainActivity.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/SharedHelper.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/all_habits.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/daily_habits.java
  app/src/main/res/layout/habit_list_item.xml
Labels: documentation

#164 java docs for abstract_habit_list_fragment,all_habits and daily-habits
  app/src/main/java/com/CMPUT301F21T19/habitappt/abstract_habit_list_fragment.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/all_habits.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/daily_habits.java
Labels: documentation

#211 Saves location data to event in db
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitEvent.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/LocationActivity.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_event.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/view_habit.java
Labels: enhancement

#214 Display visual indicator to track habit progress
  app/src/main/java/com/CMPUT301F21T19/habitappt/Habit.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/VisualIndicator.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/abstract_habit_list_fragment.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/edit_event.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/view_following.java
  app/src/main/res/layout/edit_habit.xml
  app/src/test/java/com/CMPUT301F21T19/habitappt/Habit_test.java
Labels: documentation, good first issue

#222 Added visual indicator enhancements
  app/src/main/java/com/CMPUT301F21T19/habitappt/HabitList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/VisualIndicator.java
  app/src/main/res/drawable-hdpi/ic_empty.png
  app/src/main/res/drawable-hdpi/ic_green_checkmark.png
  app/src/main/res/layout/habit_list_item.xml
Labels: enhancement

#258 changed request mode for launching map activity cause it conflicted with the camera activity
  app/src/main/java/com/CMPUT301F21T19/habitappt/Fragments/EditEvent.java
Labels: fix

#262 fixed bug where deleting an event after viewing it crashed the app wi…
  app/src/main/java/com/CMPUT301F21T19/habitappt/Activities/LocationActivity.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Fragments/EditEvent.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Fragments/ViewEvent.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Fragments/ViewHabit.java
Labels: bug, fix

#250 Some JavaDocs
  app/src/main/java/com/CMPUT301F21T19/habitappt/Activities/MainActivity.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Entities/Follower.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Entities/Following.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Entities/Request.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Entities/User.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Lists/FollowerList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Lists/FollowingList.java
  app/src/main/java/com/CMPUT301F21T19/habitappt/Lists/RequestList.java
Labels: documentation

#267 updated javadocs for visual indicators
  app/src/main/java/com/CMPUT301F21T19/habitappt/Utils/VisualIndicator.java
Labels: documentation
